export const SET_DATA_PASIEN_REGISTRASI = 'SET_DATA_PASIEN_REGISTRASI'
export const SET_DATA_PASIEN_PULANG = 'SET_DATA_PASIEN_PULANG'
export const ADD_DATA_PASIEN_PULANG = 'ADD_DATA_PASIEN_PULANG'
export const UPDATE_DATA_PASIEN_PULANG = 'UPDATE_DATA_PASIEN_PULANG'